apiVersion: v1
name: traefik2
version: 2.0.0
appVersion: 2.0.0
description: A Traefik based Kubernetes ingress controller
keywords:
- traefik
- ingress
home: https://traefik.io/
sources:
- https://github.com/containous/traefik
maintainers:
- name: emilevauge
  email: emile@vauge.com
- name: dtomcej
  email: daniel.tomcej@gmail.com
- name: ldez
  email: ludovic@containo.us
engine: gotpl
icon: http://traefik.io/traefik.logo.png
