apiVersion: v1
kind: Service
metadata:
  name: {{ template "traefik.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "traefik.name" . }}
    release: {{ .Release.Name }}
  ports:
  # HTTP entrypoint
  - port: {{ .Values.ports.http_entrypoint.port }}
    name: {{ .Values.ports.http_entrypoint.name }}
    nodePort: {{ .Values.ports.http_entrypoint.port }}
  # TCP entrypoint
  - port: {{ .Values.ports.tcp_entrypoint.port }}
    name: {{ .Values.ports.tcp_entrypoint.name }}
    nodePort: {{ .Values.ports.tcp_entrypoint.port }}
  