---
kind: Pod
apiVersion: v1
metadata:
  name: dummy-pod
  namespace: default
spec:
  containers:
    - name: dummy-pod
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]  
  restartPolicy: Never
